services:
  - type: web
    name: future-china-sync
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: SHOPIFY_SHOP
        sync: false
      - key: SHOPIFY_ADMIN_TOKEN
        sync: false
      - key: SHOPIFY_WEBHOOK_SECRET
        sync: false
      - key: SYNC_SECRET
        sync: false
